---
  pipeline: 
    000_npm-auth: 
      image: "robertstettner/drone-npm-auth"
      secrets: 
        - "npm_token"
      when: 
        event: "push"
    001_npm-build: 
      commands: 
        - "npm ci --quiet --no-progress"
        - "npm run build"
      image: "node:10-alpine"
      when: 
        event: "push"
    002_npm-unit-tests: 
      commands: 
        - "npm test"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "push"
    003_npm-audit: 
      commands: 
        - "npm audit"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "push"
    004_npm-lint: 
      commands: 
        - "npm run lint-check"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "push"
    005_npm-auth: 
      image: "robertstettner/drone-npm-auth"
      secrets: 
        - "npm_token"
      when: 
        event: "tag"
        ref: "refs/tags/*"
    006_npm-build: 
      commands: 
        - "npm ci --quiet --no-progress"
        - "npm run build"
      image: "node:10-alpine"
      when: 
        event: "tag"
        ref: "refs/tags/*"
    007_npm-unit-tests: 
      commands: 
        - "npm test"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "tag"
        ref: "refs/tags/*"
    008_npm-audit: 
      commands: 
        - "npm audit"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "tag"
        ref: "refs/tags/*"
    009_npm-lint: 
      commands: 
        - "npm run lint-check"
      group: "sanity-checks"
      image: "node:10-alpine"
      when: 
        event: "tag"
        ref: "refs/tags/*"
    010_npm-publish: 
      commands: 
        - "npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN"
        - "npm publish"
      image: "node:10-alpine"
      secrets: 
        - "npm_token"
      when: 
        event: "tag"
        ref: "refs/tags/*"

